/**
 * Enterprise Semiconductor Health & Compliance Reporting View
 */

import React, { useState, useEffect } from 'react';
import { Device, ReportData } from '../../types/index.ts';
import { api } from '../../services/api.ts';
import { useAuth } from '../../context/AuthContext.tsx';
import {
  FileText,
  Printer,
  Download,
  CheckCircle2,
  Sparkles,
  Layers,
  Cpu,
  RefreshCw,
  Clock,
  ShieldCheck
} from 'lucide-react';

export const ReportingView: React.FC = () => {
  const { user } = useAuth();
  const [devices, setDevices] = useState<Device[]>([]);
  const [selectedDevice, setSelectedDevice] = useState<string>('ST-001');
  const [reportType, setReportType] = useState<string>('DEVICE_HEALTH');
  const [report, setReport] = useState<ReportData | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    api.getDevices().then(res => setDevices(res?.devices || [])).catch(console.error);
  }, []);

  const generateReport = async () => {
    setLoading(true);
    try {
      const res = await api.generateReport({
        type: reportType,
        deviceId: selectedDevice || undefined
      });
      setReport(res.report);
    } catch (err) {
      console.error('Failed to generate report:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    generateReport();
  }, [reportType, selectedDevice]);

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      {/* Controls Header (hidden on print) */}
      <div className="print:hidden flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-slate-900 border border-slate-800 rounded-xl p-4">
        <div>
          <h1 className="text-xl font-bold text-slate-100 flex items-center gap-2.5 font-mono">
            <FileText className="w-6 h-6 text-emerald-400" />
            <span>Compliance, FMEA & Fleet Health Reports</span>
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Generate formal engineering documentation, reliability audits, and cleanroom compliance summaries.
          </p>
        </div>

        <div className="flex items-center gap-2">
          {/* Report Type */}
          <select
            value={reportType}
            onChange={e => setReportType(e.target.value)}
            className="bg-slate-950 border border-slate-700 rounded-lg px-3 py-1.5 text-xs text-slate-200 font-mono focus:border-emerald-500 outline-none"
          >
            <option value="DEVICE_HEALTH">Die Health & Reliability Audit</option>
            <option value="INCIDENT_POSTMORTEM">Incident & Escalation Post-Mortem</option>
            <option value="WHAT_IF_EVALUATION">What-If Stress Scenario Evaluation</option>
          </select>

          {/* Device */}
          <select
            value={selectedDevice}
            onChange={e => setSelectedDevice(e.target.value)}
            className="bg-slate-950 border border-slate-700 rounded-lg px-3 py-1.5 text-xs text-slate-200 font-mono focus:border-emerald-500 outline-none"
          >
            {devices.map(d => (
              <option key={d.id} value={d.id}>
                {d.id} - {d.name}
              </option>
            ))}
          </select>

          <button
            onClick={handlePrint}
            className="px-3 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold flex items-center gap-1.5 transition font-mono shadow-md"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print / Save PDF</span>
          </button>
        </div>
      </div>

      {/* Structured Print-Ready Document Canvas */}
      {loading ? (
        <div className="p-12 text-center text-slate-400">
          <RefreshCw className="w-6 h-6 animate-spin mx-auto text-emerald-400 mb-2" />
          <span>Compiling silicon telemetry and physics equations into structured report...</span>
        </div>
      ) : report ? (
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-8 max-w-4xl mx-auto space-y-6 shadow-2xl text-slate-200 font-sans print:bg-white print:text-black print:p-0 print:border-none">
          {/* Document Header */}
          <div className="border-b border-slate-800 pb-4 flex items-start justify-between">
            <div>
              <div className="text-xs font-mono font-bold uppercase tracking-widest text-emerald-400 print:text-emerald-700">
                SEMICONDUCTOR HEALTH INTELLIGENCE PLATFORM
              </div>
              <h2 className="text-xl font-bold font-mono text-slate-100 print:text-black mt-1">
                {report.title}
              </h2>
              <div className="text-xs text-slate-400 print:text-slate-600 mt-1 font-mono">
                Report ID: {report.id} • Target Package: {report.deviceId} • Generated by: {user?.name} ({user?.role})
              </div>
            </div>

            <div className="text-right font-mono text-xs text-slate-400 print:text-slate-600">
              <div>Date: {new Date(report.generatedAt).toLocaleDateString()}</div>
              <div>Time: {new Date(report.generatedAt).toLocaleTimeString()} UTC</div>
              <div className="text-emerald-400 font-bold print:text-emerald-700 mt-1">STATUS: VERIFIED</div>
            </div>
          </div>

          {/* Executive Summary */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold uppercase font-mono tracking-wider text-slate-300 print:text-slate-700">
              1. Executive Silicon Summary
            </h3>
            <p className="text-xs leading-relaxed text-slate-300 print:text-slate-800">
              {report.summary}
            </p>
          </div>

          {/* Physical Specifications & Current Readings */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold uppercase font-mono tracking-wider text-slate-300 print:text-slate-700">
              2. Die Parameters & Health Status
            </h3>
            <div className="grid grid-cols-3 gap-3 font-mono text-xs">
              <div className="p-3 bg-slate-950 print:bg-slate-100 rounded-lg border border-slate-800 print:border-slate-300">
                <div className="text-[10px] text-slate-400 print:text-slate-600">Health Index</div>
                <div className="text-lg font-bold text-emerald-400 print:text-emerald-700">{report.healthScore} / 100</div>
              </div>
              <div className="p-3 bg-slate-950 print:bg-slate-100 rounded-lg border border-slate-800 print:border-slate-300">
                <div className="text-[10px] text-slate-400 print:text-slate-600">Junction Temp (Tj)</div>
                <div className="text-lg font-bold text-slate-100 print:text-slate-900">{report.temperatureC.toFixed(1)}°C</div>
              </div>
              <div className="p-3 bg-slate-950 print:bg-slate-100 rounded-lg border border-slate-800 print:border-slate-300">
                <div className="text-[10px] text-slate-400 print:text-slate-600">Predicted Failure Risk</div>
                <div className="text-lg font-bold text-amber-400 print:text-amber-700">{(report.failureProbability * 100).toFixed(1)}%</div>
              </div>
            </div>
          </div>

          {/* Recommended Cleanroom Actions */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold uppercase font-mono tracking-wider text-slate-300 print:text-slate-700">
              3. Prescriptive Remediation Actions
            </h3>
            <ul className="space-y-1.5 text-xs text-slate-300 print:text-slate-800 font-mono">
              {report.recommendations.map((rec, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span className="text-emerald-400 font-bold print:text-emerald-700">[{i + 1}]</span>
                  <span>{rec}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Sign-off signatures */}
          <div className="pt-8 border-t border-slate-800 print:border-slate-300 grid grid-cols-2 gap-8 text-xs font-mono text-slate-400 print:text-slate-600">
            <div>
              <div className="border-b border-slate-700 print:border-slate-400 pb-1 text-slate-200 print:text-black">
                {user?.name}
              </div>
              <div className="mt-1">Reliability / Lead Operations Engineer</div>
            </div>

            <div>
              <div className="border-b border-slate-700 print:border-slate-400 pb-1 text-slate-200 print:text-black">
                SemiCore Fab QA Center
              </div>
              <div className="mt-1">Digital Twin Verification Authority</div>
            </div>
          </div>
        </div>
      ) : null}
    </div>
  );
};
